// // Server-specific Jaspr import.

// import 'package:jaspr/jaspr.dart';
// import 'package:jaspr_flutter_embed/jaspr_flutter_embed.dart';

// @Import.onWeb('walkdown_game.dart', show: [#WalkdownGame])
// import 'main.imports.dart'; // This file is generated by jaspr_builder

// class JasprApp extends StatelessComponent {
//   const JasprApp({super.key});

//   @override
//   Component build(BuildContext context) {
//     // This is a normal Jaspr component.
//     return FlutterEmbedView(
//       // // Provide an optional loader component that will be displayed while the Flutter app loads.
//       // loader: MyCustomLoader(),
//       // Provide your Flutter app widget.
//       widget: kIsWeb ? WalkdownGame() : null,
//     );
//   }
// }
